APP_NAME = "YanYiClicker"
CURRENT_VERSION = "v1.0.0 Beat"
QQ = "84284936"
QQ_GROUP = "http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=XCOQZMwDVB3y-vIz4LXdMITq-7sqGP3A&authKey=6FPrdTF0o6JIfJoc58deZ1cEWvUURazs%2FDh%2BJOz1aJI2DS%2BMFr3jRIai2%2F7bbvwN&noverify=0&group_code=84284936"
MAIN_WEBSITE = "https://gitee.com/fasterthanlight/automatic_clicker_2"
Github_WEBSITE = "https://github.com/FsterThanLight/automatic_clicker_2"
ISSUE_WEBSITE = "https://gitee.com/fasterthanlight/automatic_clicker_2/issues"
